SELECT * FROM trade_data_coll_test INTO OUTFILE 'trade.csv' FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

SELECT * FROM tick_data_coll_test_bb INTO OUTFILE 'tick_data.csv' FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';