-- SELECT * FROM trade_data INTO OUTFILE 'trade.csv' FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

SELECT * FROM tick_data INTO OUTFILE 'tick_data.csv' FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';